#include "item.h"
#include "player.h"   // Requires Player::healHP() and Player::recoverMP()

#include <iostream>
#include <sstream>
#include <stdexcept>
#include <algorithm>

// ============================================================
// Helper: convert ItemType to its integer representation
// Used for serialization.
// ============================================================
static int itemTypeToInt(ItemType t) {
    return static_cast<int>(t);
}

// Helper: convert integer back to ItemType.
// Throws std::invalid_argument for unrecognized values.
static ItemType intToItemType(int v) {
    switch (v) {
        case 0: return ItemType::HP_POTION;
        case 1: return ItemType::MP_POTION;
        default:
            throw std::invalid_argument("Unknown ItemType value: " +
                                        std::to_string(v));
    }
}

// ============================================================
// Item constructor
// Automatically generates name and description based on type
// and restore value.
// ============================================================
Item::Item(ItemType type, int value)
    : type(type), value(value)
{
    switch (type) {
        case ItemType::HP_POTION:
            name        = (value >= 100) ? "Large Health Potion"
                                         : "Small Health Potion";
            description = "Restores " + std::to_string(value) + " HP when used.";
            break;
        case ItemType::MP_POTION:
            name        = (value >= 70) ? "Large Mana Potion"
                                        : "Small Mana Potion";
            description = "Restores " + std::to_string(value) + " MP when used.";
            break;
    }
}

// ============================================================
// Item::use
// Applies the item's effect to the given player.
// Returns false without consuming the item if the relevant
// stat is already at maximum.
// ============================================================
bool Item::use(Player& player) const {
    switch (type) {
        case ItemType::HP_POTION:
            if (player.isHPFull()) {
                std::cout << "[Inventory] HP is already full. "
                          << name << " was not used.\n";
                return false;
            }
            player.healHP(value);
            std::cout << "[Inventory] Used " << name
                      << ". Restored " << value << " HP.\n";
            return true;

        case ItemType::MP_POTION:
            if (player.isMPFull()) {
                std::cout << "[Inventory] MP is already full. "
                          << name << " was not used.\n";
                return false;
            }
            player.recoverMP(value);
            std::cout << "[Inventory] Used " << name
                      << ". Restored " << value << " MP.\n";
            return true;
    }
    return false;
}

// ============================================================
// Item::serialize
// Format: TYPE|VALUE|NAME
// Example: 0|50|Small Health Potion
// ============================================================
std::string Item::serialize() const {
    return std::to_string(itemTypeToInt(type))
         + "|" + std::to_string(value)
         + "|" + name;
}

// ============================================================
// Item::deserialize
// Reconstructs an Item from a serialized string.
// Returns nullptr if the string is malformed.
// The third field (name) is informational; the name is
// regenerated by the constructor from type and value.
// ============================================================
Item* Item::deserialize(const std::string& data) {
    std::istringstream ss(data);
    std::string token;
    int typeInt, value;

    if (!std::getline(ss, token, '|')) return nullptr;
    typeInt = std::stoi(token);

    if (!std::getline(ss, token, '|')) return nullptr;
    value = std::stoi(token);

    // Third field is the name (skip — constructor regenerates it)
    return new Item(intToItemType(typeInt), value);
}

// ============================================================
// Factory methods
// Provide convenient creation of the four standard potions.
// Caller is responsible for the returned pointer unless it is
// handed to an Inventory via addItem().
// ============================================================
Item* Item::createSmallHPPotion() { return new Item(ItemType::HP_POTION,  50); }
Item* Item::createLargeHPPotion() { return new Item(ItemType::HP_POTION, 120); }
Item* Item::createSmallMPPotion() { return new Item(ItemType::MP_POTION,  30); }
Item* Item::createLargeMPPotion() { return new Item(ItemType::MP_POTION,  80); }


// ============================================================
// Inventory constructor / destructor
// ============================================================
Inventory::Inventory(int maxSize) : maxSize(maxSize) {
    items.reserve(maxSize);
}

// Destructor: delete every item still in the bag
Inventory::~Inventory() {
    for (Item* item : items) {
        delete item;
    }
    items.clear();
}

// ============================================================
// Inventory::addItem
// Transfers ownership of item to this Inventory.
// Returns false and leaves item untouched if the bag is full.
// ============================================================
bool Inventory::addItem(Item* item) {
    if (item == nullptr) return false;
    if (isFull()) {
        std::cout << "[Inventory] Bag is full (" << maxSize << "/" << maxSize
                  << "). Cannot pick up " << item->getName() << ".\n";
        return false;
    }
    items.push_back(item);
    std::cout << "[Inventory] Obtained " << item->getName() << ". ("
              << getSize() << "/" << maxSize << ")\n";
    return true;
}

// ============================================================
// Inventory::removeItem
// Permanently discards (deletes) the item at the given index.
// Does nothing if index is out of range.
// ============================================================
void Inventory::removeItem(int index) {
    if (index < 0 || index >= getSize()) return;
    delete items[index];
    items.erase(items.begin() + index);
}

// ============================================================
// Inventory::useItem
// Attempts to use the item at the given index on player.
// On success: item is consumed and removed from the bag.
// On failure: item is kept, returns false.
// ============================================================
bool Inventory::useItem(int index, Player& player) {
    if (index < 0 || index >= getSize()) {
        std::cout << "[Inventory] Invalid item index.\n";
        return false;
    }
    Item* item    = items[index];
    bool  success = item->use(player);
    if (success) {
        // Item was consumed — remove and free it
        delete item;
        items.erase(items.begin() + index);
    }
    return success;
}

// ============================================================
// Inventory::displayInventory
